image: golang:1.15

stages:
 - build
 - test

before_script:
 # Create a symbolic link under $GOPATH, this is needed for local build
 - cd $GOPATH/src
 - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
 - cd gitlab.com/$CI_PROJECT_NAMESPACE
 - ln -s $CI_PROJECT_DIR
 - cd $CI_PROJECT_NAME

project-build:
 stage: build
 script:
   # - godep restore
   # - godep go build
   - go get ./...
   - go build -v -ldflags="-X main.date=`date -I$TIMESPEC`"; date -I$TIMESPEC

project-test:
 stage: test
 script:
   # - godep restore
   # - godep go test -v -cover ./...
   - go get ./...
   - go test -v -cover ./...
