# -*- yaml -*-

language: go

env:
  global:
    - VERSION="${TRAVIS_TAG:=0.0~git$(date +%Y%m%d)-1}"
   # Build time setup
    - TZ=America/Toronto
    - DATE_BUILD=`date -I`

script:

  - date
  - echo $DATE_BUILD $VERSION
  - echo

  - go get -t -v ./...
  - go build -v -ldflags="-X main.date=$DATE_BUILD"
  - wireframe
  - go test -v ./...

